// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotesCore.Models.Context;

namespace NotesCore.Migrations
{
    [DbContext(typeof(NotesContext))]
    partial class NotesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NotesCore.Models.Note", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AlreadyDeleted");

                    b.Property<DateTime>("CreationDate");

                    b.Property<int?>("DaysDeleting");

                    b.Property<bool>("DeleteAfterRead");

                    b.Property<DateTime?>("DeletingDate");

                    b.Property<string>("GuidNote");

                    b.Property<string>("GuidNote1");

                    b.Property<int?>("HoursDeleting");

                    b.Property<int?>("MinutesDeleting");

                    b.Property<string>("NoteText");

                    b.Property<int?>("SecondsDeleting");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
